title: Hello, world! I'm Cara Brook
description: > # this means to ignore newlines until "baseurl:"
  Notes from the Eighth Continent
permalink: ':title/'
base-url: /blog
url: carabrook.github.io
url: https://blog.nationalgeographic.org/author/carabrook/
github: [metadata]


# Author Settings
author: Cara Brook # add your name
author-img: cara_makira.JPG # add your photo
about-author: I am a UC Berkeley Miller Fellow chasing bat viruses across Madagascar. Follow me here and on National Geographic Voices.
github: carabrook # add your Github handle
email: cbrook@berkeley.edu

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
