title: Brook Lab News
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
base-url: /blog
url: brooklab.org
github: [metadata]


# Author Settings
author: Brook Lab # add your name
author-img: ekipa_fanihy_happy.jpg # add your photo
about-author: The Brook Lab shares news and views from the field, the lab, and the office!
github: brooklabteam # add your Github handle
email: cbrook@berkeley.edu
url: brooklab.org
twitter: caraebrook

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji


paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
